### PR TITLE
Omit non DOM props

### PR DESCRIPTION
**Pull request by salzhrani**
addresses react 15.2.0 warnings

### CODE REVIEW

**Comment by willdurand** [comment]
:+1:

**Comment by chrisui** [comment]
Cheers for the pull request! Sorry for the delay, I've been on holiday!

I'm going to tidy this up and get it merged and published today.

**Comment by chrisui** [comment]
Have released a fix for this with `v0.9.0`.

Release diff: https://github.com/chrisui/react-hotkeys/compare/v0.8.0...v0.9.0?expand=1

Thanks!

**Comment by willdurand** [comment]
awesome, thanks!

**Pull request closed without merging**
