### PR TITLE
Bumping to React 15

### PR DESCRIPTION
**Pull request by stevewillard**

### CODE REVIEW

**Comment by Chrisui** [comment]
Hey @stevewillard would you mind making the peer dependencies `>= 0.14.0` for those of us who haven't the luxury of upgrading just yet! :D 

I believe this is the correct way to handle peer dependencies as it just specifies a *minimum* required version supported.

**Comment by Chrisui** [comment]
And of course, thank you very much!

**Comment by stevewillard** [comment]
Sure thing 👍

**Comment by Chrisui** [comment]
Cheers!

**Comment by Chrisui** [comment]
Released with v0.8.0.

Thanks for the contribution!

**Pull request merged**
