### PR TITLE
Update React to 15.5 and fix PropTypes and createClass

### PR DESCRIPTION
**Pull request by slate71**
Simply followed the instructions for updating `PropTypes` and `createClass` to 15.5 from the React blog:
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

Then ran lint, test, and build scripts.

Also added `babel-register`, the test script required it.

### CODE REVIEW

**Comment by kelyvin** [comment]
+1 👍

**Comment by chrisui** [comment]
👍 cheers

sorry it's took me a while to action this! Will get a new release out asap.

**Comment by chrisui** [comment]
Released in [v0.10.0](https://www.npmjs.com/package/react-hotkeys)

**Comment by kelyvin** [comment]
Thanks!

**Comment by slate71** [comment]
Great, thanks!

**Pull request merged**
