### PR TITLE
Simple typescript typings.

### PR DESCRIPTION
**Pull request by admmasters**

### CODE REVIEW

**Comment by Chrisui** [comment]
Cool, cheers! Happy to merge this but will need to update our scripts to ensure that this is bundled into an npm package.

Would you mind adding a quick line to https://github.com/Chrisui/react-hotkeys/blob/master/scripts/build-npm in order to copy the type file into the npm package?

Thanks again!

**Comment by admmasters** [comment]
Ah sure, will do!

**Comment by Chrisui** [comment]
👍 thanks!

**Comment by Chrisui** [comment]
Released with v0.8.0.

Thanks for the contribution!

**Pull request merged**
