### PR TITLE
Update examples to React 16

### PR DESCRIPTION
**Pull request by sapegin**

### CODE REVIEW

**Comment by greena13** [comment]
It was mentioned in #72 that this pull request updates the package to react 16. From what I can see, it only updates the example files - and none of the files in `lib`. 

I'm not suggesting the scope of this pull request should be expanded - just checking my understanding of what is and is not included.

**Comment by sapegin** [comment]
Yep, but the example works with React 16 without any changes to the library itself. If there are any issues with React 16 like #67 (not sure if it’s still relevant), they aren’t reproducible on the example.

**Comment by greena13** [comment]
So if I understanding you correctly, @sapegin, you are saying that this PR updates the example usage of this library to demonstrate usage with a React 16 project and to get it working with React 16, you found no changes to the library were necessary - but there is some suggestion (i.e #67) that it may not work with some React 16 project?

This PR does change dependency versions, which I would prefer to do in a separate release. I would like the first release to contain all the outstanding PRs without upgrading the version of React to allow for those who have had to fork this repo to get the changes made in the PRs, but who haven't necessarily upgraded to React 16 or above. 

The second release, semantically versioned to suggest breaking changes, will contain all changes necessary to upgrade the example and source code to React 16.

So if my understanding above is correct, this PR looks OK to me, but will be merged at a later date - not too far into the future - as part of the efforts to upgrade to support React 16.

**Comment by sapegin** [comment]
> So if I understanding you correctly, @sapegin, you are saying that this PR updates the example usage of this library to demonstrate usage with a React 16 project and to get it working with React 16, you found no changes to the library were necessary - but there is some suggestion (i.e #67) that it may not work with some React 16 projects?

Yes, exactly. I guess that issue is no longer relevant because it was created before React 16 final release.

> This PR does change dependency versions, which I would prefer to do in a separate release. I would like the first release to contain all the outstanding PRs without upgrading the version of React to allow for those who have had to fork this repo to get the changes made in the PRs, but who haven't necessarily upgraded to React 16 or above.

It changes dev dependencies, plus minor updates of production dependencies, so they are no breaking changes for the package consumer. But it, of course, may require some updates of other PRs.

> The second release, semantically versioned to suggest breaking changes, will contain all changes necessary to upgrade the example and source code to React 16.

Again, there are no breaking changes for package consumer, so don’t need to make a new release after this PR. Correct me if I’m missing something.

**Comment by greena13** [comment]
Ah, you are quite right. I either mis-read the changes or conflated dependency changes with peer dependency changes. Either way, from what I understand, I agree that these changes should not change the outward behaviour of the package and therefore do not need to be included in a version that suggests changes.

Thank you for your work on this.

If you are interested and have the time to contribute further, I am trialling out coordinating further efforts and sharing of work through gitter https://gitter.im/chrisui/react-hotkeys.

**Pull request merged**
