### PR TITLE
Update to React 0.14

### PR DESCRIPTION
**Pull request by cpsubrian**
As far as I know:

- Tests pass
- Examples work (though for me backspace wasn't captured, it navigated Back)

I did multiple commits so you can look at the actual lib changes separate from the built files.

### CODE REVIEW

**Comment by smashercosmo** [comment]
@cpsubrian awesome, thx) waiting for merge

**Comment by Chrisui** [comment]
Awesome. Would you mind removing the additions to the `build/`folder as they are part of the release process and should be avoided in these PR's :)

Soon as that's done I\'ll merge!

Really appreciate it @cpsubrian !  :)  So busy with moving house and stuff atm.

**Comment by cpsubrian** [comment]
Force-pushed without the build commit. Note: Pretty sure I had to downgrade to Node `0.12.7` to get the tests to run. Probably just a dependency tree thing.

**Comment by Chrisui** [comment]
:+1: Cheers! Will get this published asap.

**Comment by goldensunliu** [comment]
what's the update on this, right now I am npm installing straight from the repo to get the master branch

**Comment by Chrisui** [comment]
Just published `v0.6.0` on npm! :)

Sorry for the delay was having some troubles with jsdom (aware that it requires a much more modern version of node than I have).

Give me a shout if there are any issues and I'll try to get them resolved asap this weekend!

**Pull request merged**
